version: "3.8"
services:
  db:
    image: postgres:15
    container_name: tts_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tts
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata: